language: ruby
sudo: false
rvm:
  - 2.2.5
cache:
  bundler: true
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database elixr_test' -U postgres
  - npm install bower -g
  - bower install
before_install:
  - gem install selenium-webdriver
