language: ruby
sudo: false

rvm:
  - 2.1.2
    
cache:
  bundler: true

addons:
  postgresql: "9.4"

before_script:
  - mysql -u root -e "create database elixr_test;"
  - bundle exec rake db:schema:load RAILS_ENV=test
